name: Cypress Tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # Adjust this based on your project setup

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: path/to/your/build  # Adjust this based on your project setup

  cypress-run:
    runs-on: ubuntu-latest

    needs: build

    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download the build folder
        uses: actions/download-artifact@v4
        with:
          name: build

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: true
          group: 'UI-Chrome'
          start: npm start  # Adjust this based on your project setup
